### ISSUE TITLE
Variable css classes used while processing need to be parent classed.

### ISSUE THREAD

**Issue by mtgibbs** [mtgibbs/gulp-less-branding-js#2]
To avoid issues with colliding with existing classes if the user decides to use a .less file that has actual classes to be output there needs to be a parent class on each of the created classes that holds the value.

``` less
@brand: red;
@brand-some-existing-class-name: blue;
```

Generates in interim to:

``` css
.brand {
    color: red;
}
.brand-some-existing-class-name {
    color: blue;
}
```

In this case it's likely that we will grab the wrong value when building the variable dictionary.

Suggested Solution

Wrap the variables to be added with a parent class in the interim less file to produce output like this:

``` css
.gulp-less-branding-js.brand {
    color: red;
}
.gulp-less-branding-js.brand-some-existing-class-name {
    color: blue;
}
```

Then only pull info from selectors that are marked with the plugin's parent class.
